services:
  api-talentpool:
    container_name: api-talentpool
    build:
      context: .docker/node
      dockerfile: Dockerfile
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - "3000:3000"
      - "7000:7000"
    volumes:
      - .:/home/node/app

  db-template:
    container_name: db-talentpoolapi
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 8745
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api-talentpool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8745:8745"
