services:
  api-talentpool-test:
    container_name: api-talentpool-test
    build:
      context: .docker/node
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - "3001:3000"
      - "7001:7000"
    volumes:
      - .:/home/node/app
    depends_on:
      db-talentpool-test:
        condition: service_healthy

  db-talentpool-test:
    container_name: db-talentpool-test
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 5001
    environment:
      POSTGRES_DB: api-talentpool-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5001"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5001" ]
      interval: 5s
      timeout: 5s
      retries: 5
